### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by praveen-rikhari** [sak345/Campeazy#3]
Hey brother please help

**Comment by praveen-rikhari** [comment]
hey brother currently I am also working on the same project but I am stuck while updating the images of campground it shows me the same error again  **_Error:"image" is not allowed at module.exports.validateCampground_**.
Could you please help me...

**Comment by sak345** [comment]
> hey brother currently I am also working on the same project but I am stuck while updating the images of campground it shows me the same error again **_Error:"image" is not allowed at module.exports.validateCampground_**. Could you please help me...

One of the reasons for this problem can be that in your `campgroundSchema` (Joi Schema defined for `validateCampground` function) you might not have defined a rule for image, you need to add `image: Joi.array()` in the Joi campgroundSchema. Now, during validation, an array of images is expected and probably will not throw an error.
If the error still exists then share your code where you've defined Joi campgroundSchema.
